### ISSUE TITLE
Preformatted code blocks are ignored

### ISSUE THREAD

**Issue by sebastien** [nknapp/bootprint-swagger#16]
The code (below) between triple backquotes is not output in the bootprint HTML file:

    swagger: "2.0"
    info:
        title: XXX
        description: XXX
        version: "0.1"
    host:
        api.xxx.org
    schemes:
        - https
    produces:
        - application/json
    paths:

        /foo/bar:
          get:
            summary: Foo bar
            description: |
                  Lorem ipsum dolor sit amet
                  ```{
                  id   : "xxx",
                  xxx:["xxx"
                  name : {
                  en:" xxxx",
                  fr:""
                  }
                  ```
            responses:
              200:
                description: |
                  Lorem ipsum
                schema:
                  type: integer

**Comment by nknapp** [comment]
I guess it should be 
    ```
    {
instead of 
   ```{
right? I've verified the bug.

**Comment by nknapp** [comment]
I've fixed it and possible #17 as well. 
Could you please verify using `bootprint-swagger@0.6.3` and `bootprint-base@0.5.1`.

**Comment by nknapp** [comment]
Closing. Please comment if anything still does not work

**Comment by sebastien** [comment]
I confirm this is now fixed, many thanks!
