### ISSUE TITLE
Empty lines in descriptions swallow the contents

### ISSUE THREAD

**Issue by sebastien** [nknapp/bootprint-swagger#17]
In the YAML file below, the first line is displayed but the second one is swallowed. Removing the newline makes the second line appear in the documentation.

    swagger: "2.0"
    info:
        title: XXX
        description: XXX
        version: "0.1"
    host:
        api.xxx.org
    schemes:
        - https
    produces:
        - application/json
    paths:

        /foo/bar:
          get:
            summary: Foo bar
            description: |
                  First line is displayed

                  Second line is swallowed
            responses:
              200:
                description: |
                  Lorem ipsum
                schema:
                  type: integer

**Comment by nknapp** [comment]
Hello Sebastien,

I haven't done much with YAML yet. It's not my favorite language (yet). But if you put the YAML through `bootprint-swagger` I guess you have converted it to JSON before.

Could you post this JSON? Or even better, add a JSON file to the `spec/fixtures/` directory in a Pull-Request. 
It would be best to write a test case (similar to the ones in `spec/petstore-spec.js`) to reproduce this issue, but if you post the JSON, I can write the test.

**Comment by nknapp** [comment]
This may have been fixed in the current version.
Could you please verify using `bootprint-swagger@0.6.3` and `bootprint-base@0.5.1`.
I'm leaving this issue open. Please close after verification

**Comment by nknapp** [comment]
Closing. Please comment if anything still does not work

**Comment by sebastien** [comment]
I confirm this is now fixed, many thanks!
