### ISSUE TITLE
Parameters of type `body` not being displayed

### ISSUE THREAD

**Issue by asieira** [nknapp/bootprint-swagger#19]
I have entries with parameters where `in` equals `body`, but none of them are being displayed in the HTML output.

Here's an excerpt of the JSON:
```
    "paths": {
        "/thingy": {
            "post": {
                "summary": "Create new thingys.",
                "tags": [
                    "Thingys",
                    "Back-End Only"
                ],
                "description": "Adds new thingys to the database, assigning them IDs and setting their last modification date/time to now.\n",
                "parameters": [
                    {
                        "name": "thingys",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Thingy"
                            },
                            "minItems": 1
                        },
                        "description": "An array of thingys to add to the database.\n"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The thingys successfully inserted, complete with IDs and last modification fields.\n",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Thingy"
                            },
                            "minItems": 1
                        }
                    },
                    "400": {
                        "$ref": "#/responses/bad_request"
                    },
                    "403": {
                        "$ref": "#/responses/unauthorized"
                    }
                }
            }
        }
```

BTW, the definitions are being expanded using [swagger-expand-refs](https://github.com/duncanhall/expand-swagger-refs) prior to submission to bootprint-swagger since they were causing issues.

When I generate the HTML, the `Request Parameters` section is simply not displayed at all, it goes straight from `Description` to `Response Body`.

**Comment by nknapp** [comment]
Thank you for the report. I've just created a new version or bootprint-swagger (0.6.4). It should solve the problem. It would be great if you could verify.

In version 0.6.3, the request body and the whole section around it, is only displayed if a `consumes`-property is present in the `operation`-object. I actually think, your operation should have one, but I have relaxed the condition, so that either a `consumes`-property or a `body`-parameter must be present.

**Comment by asieira** [comment]
According to the swagger spec, the [main object](http://swagger.io/specification/#swaggerObject) can contain global `consumes` and `produces` entries that apply to all paths and operations unless overriden. So requiring a `consumes` at the operation level should not be necessary.

**Comment by asieira** [comment]
Just confirmed that 0.6.4 did solve the issue, thank you very much! :)

**Comment by nknapp** [comment]
I've created issue #20 to display the global default values. I'm not sure about the best way to display them. If you have an oppinion, you could comment there. That would be great

**Comment by asieira** [comment]
I'd add something at the very top, before the operations summary, that covers this and the authentication/security options.

**Comment by nknapp** [comment]
Cool, thanks.

**Comment by nknapp** [comment]
Could you post your whole JSON here as well? I would like to add support for the response-`$ref`s.

**Comment by asieira** [comment]
As soon as I make it public (in a week or two), I will post the link here. Meanwhile, more than happy to share it privately with you so you can conduct testing with it, provided you don't make it public anywhere.

**Comment by nknapp** [comment]
I guess `bootprint-swagger` will survive the next two weeks without being able to display response-refs. I can also create my own example. It's just less work for me if someone else does it.

For me, testing means including a spec as test-fixture in the project and writing a unit test. Maybe a dedicated fixture is better suited for this task anyway.

**Comment by asieira** [comment]
How about this one?
```
{
    "swagger": "2.0",
    "info": {
        "title": "Test API",
        "version": "v1-beta"
    },
    "host": "api.contoso.com",
    "schemes": [
        "https"
    ],
    "basePath": "/api/v1-beta",
    "securityDefinitions": {
        "api_key": {
            "name": "X-API-KEY",
            "type": "apiKey",
            "in": "header"
        }
    },
    "security": [
        {
            "api_key": []
        }
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/tagged_things": {
            "get": {
                "summary": "List tagged things.",
                "tags": [
                    "Alerts"
                ],
                "description": "Lists all tagged things accessible to the API key owner.\n",
                "responses": {
                    "200": {
                        "description": "An array of tagged things",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": [
                                    "tags"
                                ],
                                "properties": {
                                    "tags": {
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "enum": [
                                                "option1.blah",
                                                "option2.bleh"
                                            ],
                                            "minLength": 1,
                                            "maxLength": 64
                                        },
                                        "uniqueItems": true,
                                        "description": "Array containing one or more tags.\n"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "$ref": "#/responses/bad_request"
                    },
                    "403": {
                        "$ref": "#/responses/unauthorized"
                    }
                }
            }
        }
    },
    "responses": {
        "bad_request": {
            "description": "The request violated the specification and was rejected. The reason string should contain more details on the specific error."
        },
        "unauthorized": {
            "description": "Operation was not allowed due to an invalid API key, insufficient privileges or trying to reference an entity that does not exist. We have purposedfully combined non-existance and lack of privileges into this error code to avoid enumeration attacks."
        }
    }
}
```

**Comment by nknapp** [comment]
That's great. Thanks. Just to make sure that's OK. I have included your other samples in my test fixtures: 
 [body-without-consume.json](https://github.com/nknapp/bootprint-swagger/blob/master/test/fixtures/body-without-consume.json), [missing-items.json](https://github.com/nknapp/bootprint-swagger/blob/master/test/fixtures/missing-items.json), so that was like putting them under MIT-license with the rest of the `bootprint-swagger`-code. There is no good way to include a licensing-comment in JSON, so I will put an extra file somewhere in the project mentioning you as author somehow. 

I would just to ask for permission to do this. If you say "take them out again" I will do that and create my own. Same for the JSON you just posted.

Is it OK to include them in the project under the MIT-License?

**Comment by asieira** [comment]
Yes, feel free to add those examples into the project under MIT License. I'm glad I was able to help. :)
