### ISSUE TITLE
Cannot find template.hbs

### ISSUE THREAD

**Issue by solsend2l** [nknapp/bootprint-swagger#2]
When I run:
`$ bootprint swagger http://localhost:63342/blee2/documentation/api.json documentation/`

I get:
`{ [Error: Cannot find module './template/template.hbs'] code: 'MODULE_NOT_FOUND' }`

**Comment by nknapp** [comment]
This was an error in Bootprint-base. The bug was already fixed, but not published. Now it is. Make sure that `bootprint-base` version 0.2.3 is loaded as dependency of `bootprint-json-schema`.
Thanks for reporting

**Comment by nknapp** [comment]
closing
