### ISSUE TITLE
Doesn't parse Markdown in the info description

### ISSUE THREAD

**Issue by KingMob** [nknapp/bootprint-swagger#3]
E.g., in the following, the description emerges as plain text, despite having GitHub-flavored Markdown inside.

```json
{
    "swagger": "2.0",
    "info": {
        "title": "SmartGift API",
        "description": "This is the API to manage blah. The API is more extensive than is presented here, but in the interests of simplification, we are only presenting part of it. You typically will need to call on only **3 endpoints**: ```GET /emails```, ```POST /products```, and  ```POST /cereal```. To see just the most-relevant endpoints, filter by the \"Frequently Used\" tag.",
        "version": "1.0.0",
        "contact": {
            "name": "API Support",
            "url": "http://developers.smartgiftit.com",
            "email": "support@smartgiftit.com"
        }
    },
```

**Comment by nknapp** [comment]
I have fixed this. Please verify, by doing `npm install -g nknapp/bootprint-swagger` to install the module from the github-repo. I will probably not be able to make a new release until monday.

**Comment by nknapp** [comment]
By the way, if you find more like this and are interesting in fixing it yourself: 
* You can find the partials in "handlebars/partials". This one was in "handlebars/partials/base/body.hbs".
* Everything used for displaying models and JSON-schema is in the [bootprint-json-schema](https://github.com/nknapp/bootprint-json-schema)-repo.
* Calling the markdown-parser is done by the `md`-helper, so what I did was just to changing. 
`<p>{{{info.description}}}</p>` to `<p>{{md info.description}}</p>`

I'm still looking for a good way to document the template-modules, such that comments withing the templates, less-files and helper-definitions are parsed and can be included easily. Once I find one, I will write documentation too...

**Comment by nknapp** [comment]
Version 0.5.0 parses the "info.description"
