### ISSUE TITLE
Parameters referenced by $ref tag should display the parameters as if it is inline

### ISSUE THREAD

**Issue by Sauradyuti** [nknapp/bootprint-swagger#30]
I would like the parameters which are referenced using a $ref tag o be displayed in a similar way as the parameters which are defined inline are displayed.

I have parameters referenced using $ref tags as shown in the image below:
<img width="358" alt="screen shot 2015-09-16 at 2 04 38 pm" src="https://cloud.githubusercontent.com/assets/2540728/9900090/f9bf3a52-5c7b-11e5-876b-c3356cbc8485.png">

I would like these parameters to be displayed like the inline parameters as shown below:
<img width="780" alt="screen shot 2015-09-16 at 2 08 12 pm" src="https://cloud.githubusercontent.com/assets/2540728/9900147/7095d3f2-5c7c-11e5-875b-1c0933af0670.png">

**Comment by nknapp** [comment]
Agreed. It should be recognizable as default parameter though.

**Comment by Sauradyuti** [comment]
I have already modified bootprint-swagger/handlebars/partials/swagger/parameters.hbs and bootprint-swagger/node_modules/bootprint-json-schema/handlebars/helpers.js to do it. Would you mind taking a look?

**Comment by Jasmee** [comment]
I am looking for this too.. would be great to have this feature included.

**Comment by nknapp** [comment]
@Sauradyuti What do you mean by "taking a look"? If you want to create a pull-request, that would be great.

**Comment by nknapp** [comment]
I've had a look at your pull-requests. Thanks for submitting them. However, I think I have found a simple and cleaner solution. I'm not finished yet. Testcases still need to be adapted. But if you want to have a look it, you can checkout the branch "feature/inline-global-params" on each `bootprint-json-schema` and `bootprint-swagger`

**Comment by nknapp** [comment]
Resolved in 0.7.0
