### ISSUE TITLE
"allOf" renders incorrect HTML doc

### ISSUE THREAD

**Issue by msh321** [nknapp/bootprint-swagger#35]
I have tried to use the online "playground" (http://bootprint.knappmeier.de/) to generate HTML docs for the following Swagger specification:

```json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "TODO",
    "version" : "0.0.1",
    "title" : "API Spec",
    "termsOfService" : "TODO"
  },
  "basePath" : "/v1",
  "schemes" : [ "http", "https" ],
  "paths" : {
    "/aaa" : {
      "post" : {
        "tags" : [ "AAA" ],
        "summary" : "TODO",
        "description" : "TODO",
        "operationId" : "aaa",
        "consumes" : [ "application/json", "application/xml" ],
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "TODO",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/AAA"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Authentication was successful"
          },
          "405" : {
            "description" : "Invalid data"
          }
        }
      }
    }
  },
  "definitions" : {
    "AAA" : {
      "allOf" : [ {
        "$ref" : "#/definitions/BBB"
      }, {
        "type" : "object",
        "properties" : {
          "ttt" : {
            "type" : "string"
          }
        }
      } ]
    },
    "BBB" : {
      "allOf" : [ {
        "$ref" : "#/definitions/CCC"
      }, {
        "type" : "object",
        "properties" : {
          "vvv" : {
            "type" : "string"
          }
        }
      } ]
    },
    "CCC" : {
      "type" : "object",
      "properties" : {
        "uuu" : {
          "type" : "string"
        },
        "ppp" : {
          "type" : "string"
        }
      }
    }
  }
}
```

I really like the generated API docs, but unfortunately the objects `AAA` and `BBB` appear to be empty although they both contain properties.

Clearly, it seems like the use of `allOf` is not properly handled by `bootprint-swagger`.

If I convert the JSON specification to YAML and paste it to the Swagger Editor (http://editor.swagger.io/) then the objects `AAA` and `BBB` are correctly displayed.

**Comment by nknapp** [comment]
Mhm, I have to check why this happened. I had this working already, but I didn't have tests. Time to write some...

**Comment by msh321** [comment]
I will gladly volunteer to test an early fix.
:)

**Comment by nknapp** [comment]
Should be fixed with bootprint-json-schema@0.7.1. This was a regression introduced in bootprint-json-schema@0.5.2 along with the fix for #26. 

I've taken the liberty to create a testcase based on your example. I hope it is OK to include it in the project (which is licensed under MIT-license). Otherwise please tell me (here or by e-mail) and I'll write my own example.

Can you verify the fix?

**Comment by nknapp** [comment]
The fix is not on the playground yet. Give me a couple of minutes.

**Comment by nknapp** [comment]
Now its there

**Comment by msh321** [comment]
It's fine to use my example in the test.
I will make a test of the fix tomorrow morning.
Thanks!

**Comment by msh321** [comment]
I have tested the 0.9.1 version with my _real_ Swagger Specification and it seems to work fine.  :smiley: 

Thanks a lot for the quick response!
