### ISSUE TITLE
Issues with global responses

### ISSUE THREAD

**Issue by msh321** [nknapp/bootprint-swagger#39]
When defining a REST API it is convenient to be able to define a list of "global" responses that can be referenced from multiple REST methods.  However, when using this feature, the HTML document rendered by Bootprint Swagger looks wrong.

See this example:

```json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "TODO",
    "version" : "0.0.1",
    "title" : "API Spec",
    "termsOfService" : "TODO"
  },
  "basePath" : "/v1",
  "schemes" : [ "http" ],
  "paths" : {
    "/aaa" : {
      "post" : {
        "tags" : [ "AAA" ],
        "summary" : "TODO",
        "description" : "TODO",
        "operationId" : "aaa",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "body",
          "description" : "TODO",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/AAA"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success"
          },
          "401" : {
            "$ref" : "#/responses/401"
          },
          "405" : {
            "description" : "Invalid data"
          }
        }
      }
    }
  },
  "definitions" : {
    "AAA" : {
      "allOf" : [ {
        "$ref" : "#/definitions/BBB"
      }, {
        "type" : "object",
        "properties" : {
          "propA" : {
            "type" : "string"
          },
          "propB" : {
            "type" : "string"
          }
        }
      } ]
    },
    "BBB" : {
      "type" : "object",
      "properties" : {
        "propA" : {
          "type" : "string"
        }
      }
    },
    "UnauthorizedResponse" : {
      "type" : "object",
      "properties" : {
        "code" : {
          "type" : "integer",
          "description" : "Error code."
        },
        "test" : {
          "type" : "string",
          "description" : "Error message."
        }
      }
    }
  }
```

In the rendered documentation for the `/aaa` REST method there should be a reference to the definition of the `UnauthorizedResponse` object.  But instead there is a "dead" reference to `#/responses/401`.

**Comment by msh321** [comment]
BTW: Here's a screenshot of the rendered `/aaa` REST method:

![bp3](https://cloud.githubusercontent.com/assets/1345452/10205516/e1a7eabc-67c1-11e5-96e0-12b9e8fce0ea.png)

As you can see in the orange box, there is a reference to `#/responses/401` which is not of much help to the reader of the document.  :smiley: 

Interestingly, there is a `global` label -- so Bootprint Swagger seems to know about global responses...

**Comment by nknapp** [comment]
I haven't tested it, but I would say the problem is, that you haven't included a global response-definition in your JSON. If you reference to `#/responses/401` the swagger-definition should have a `responses`-property like [this test-fixture here](https://github.com/nknapp/bootprint-swagger/blob/master/test/global-responses/swagger.json). 

What you see in your output is just the header (http-status, global-marker, reference to global response (I thought it is nice to have the reference, even if the contents is inlined)). The actual inlined part is missing because the reference to `#/responses/401` cannot be resolved.
I guess I should add an error-message for such a case [in the corresponding helper](https://github.com/nknapp/bootprint-json-schema/blob/master/handlebars/helpers.js#L34) instead of just ignoring it.

**Comment by msh321** [comment]
Hmmm -- you're right...

Actually, I wrote the specification in YAML and converted it to JSON using Swagger Codegen.  In the YAML version I do have the `response`-property defined (containing the global responses), but when I convert it to JSON it seems to get lost.

Hence, this seems to be an issue with Swagger Codegen (and not Bootprint Swagger).  I will make some more tests and raise an issue in the Swagger Codegen project...

Sorry for the false alarm.

__BTW:__ Do you have any plans for supporting YAML as input instead of JSON?

**Comment by msh321** [comment]
So, now I am using a generic YAML to JSON converter:

* https://www.npmjs.com/package/yamljs

That seems to work -- Bootprint Swagger now renders my global responses as expected.

Feel free to close this issue!  :smirk_cat:

**Comment by msh321** [comment]
Oh -- I just close the issue myself!  :stuck_out_tongue_winking_eye:

**Comment by nknapp** [comment]
I'll keep the issue open to remind myself to  add an error-message for such a case [in the corresponding helper](https://github.com/nknapp/bootprint-json-schema/blob/master/handlebars/helpers.js#L34) instead of just ignoring it.

**Comment by nknapp** [comment]
@msh321 see [this issue about YAML support](https://github.com/nknapp/bootprint/issues/4). I'm currently occupied otherwise, but I have no objections for including it.

**Comment by nknapp** [comment]
In `bootprint-json-schema@0.8.0`, an error is thrown when attempting to resolve an invalid reference.
