### ISSUE TITLE
Required parameters info is not captured

### ISSUE THREAD

**Issue by jsachania** [nknapp/bootprint-swagger#4]
I have marked some parameters as required [e.g. in swagger.json - "required": true ] but in the generated documentation there is no indication that the parameter is required in the request. Red asterisk or a label indicating that the parameter is required would help.

**Comment by nknapp** [comment]
Can you provide a simple example json?

**Comment by jsachania** [comment]
You can use http://petstore.swagger.io/v2/swagger.json as example json. 

DELETE /pet/{petId} has petId as required.

**Comment by nknapp** [comment]
oh, thanks

**Comment by nknapp** [comment]
I've added the 'required`-badge that is also used in the JSON-schema. Try the newest version.

**Comment by jsachania** [comment]
It looks good now. Thanks.
