### ISSUE TITLE
Wrong default request / response content-types

### ISSUE THREAD

**Issue by PaddeK** [nknapp/bootprint-swagger#40]
The Default request content-types and Default response content-types both list
the consumes field of the swagger object. 
The corresponding handlebar body.hbs needs to be changed to:

    <div id="sw-default-consumes" class="sw-default-value">
        <span class="sw-default-value-header">Default request content-types:</span>
        {{#each consumes}}{{.}}{{#unless @last}}, {{/unless}}{{/each}}
    </div>
    <div id="sw-default-produces" class="sw-default-value">
        <span class="sw-default-value-header">Default response content-types:</span>
        {{#each produces}}{{.}}{{#unless @last}}, {{/unless}}{{/each}}
    </div>

Also both are always created even if no consumes or produces is given in the swagger
object.

**Comment by nknapp** [comment]
Hi there, thanks for reporting this issue. I have fixed it, but I haven't created a test-case yet. Could you verify with `bootprint-swagger@0.9.2` ?

**Comment by PaddeK** [comment]
Works perfectly! Thanks for the quick fix :)
