### ISSUE TITLE
nothing happens when running bootprint swagger

### ISSUE THREAD

**Issue by bendavis78** [nknapp/bootprint-swagger#49]
When I run `bootprint swagger http://petstore.swagger.io/v2/swagger.json doc`, I get the following output:
```
Loading bootprint-swagger 0.13.1
Loading bootprint-json-schema 0.8.4
Loading bootprint-base 0.6.3
```
But nothing happens after that. No files were put in the doc directory.

**Comment by nknapp** [comment]
Hi there,

have you made a fresh install or have you updated your version? Have a look at bootprint#12. This issue has appeared 2 days ago and should be resolved by now... You may have to clear the npm-cache, remove bootprint and reinstall to get the current version of `deep-aplus` (@1.0.2)

**Comment by bendavis78** [comment]
That was it, thanks!
