### ISSUE TITLE
POST/PUT Request payload JSON schema is not captured

### ISSUE THREAD

**Issue by jsachania** [nknapp/bootprint-swagger#5]
In the requests where payload is JSON object then the type (or schema) is not captured in the document. Instead the data type is shown as 'object'. 

 - Use  http://petstore.swagger.io/v2/swagger.json model to generate a doc
 - Check the request 'POST /pet'. See the REQUEST PARAMETERS section. The data type of the parameter is 'object'. Expected: 'Pet' with link to view the Pet JSON schema
 - Compare it with the out of box Swagger UI or Swagger Editor where they have captured schema of JSON.

**Comment by nknapp** [comment]
Thanks, I hadn't noticed that. It actually worked some time ago, but during some refactorings, the 'preprocessor.js` was lost. It was responsible to extracting the `body` parameter into its own json-property so that it could be displayed separately by Handlebars.

**Comment by nknapp** [comment]
Try the new version `0.5.3`. If there are any errors, make sure that `bootprint-base@0.3.0` is used as dependency and `bootprint@0.4.9` is installed globally.
I have published both packages with fixes that are needed for `bootprint-swagger@0.5.3` to work. 
Since those are all 0.x versions, I don't take much care of semantic versioning right now.

Could you close the issue, once you've verified the bugfix?

**Comment by jsachania** [comment]
Thanks. The issue seems to be resolved but now method types (GET, POST, PUT etc) are displayed as `function toUpperCase() { [native code] }` code in the summary section as well as in the details.

**Comment by nknapp** [comment]
Mhm, this was an old commit in `bootprint-base` that got published with 0.3.0. I fixed it and wrote a test.
If you do `npm install -g bootprint-swagger`, you should get `bootprint-base@0.3.1`.
I have also published a new version of `bootprint` which prints the versions of the template-modules used. (This may configurable by cli-arguments some time, but at the moment, it just prints them).

**Comment by jsachania** [comment]
It looks good now. Versions are also printing. Thanks!
