### ISSUE TITLE
Put css in html file so that only 1 file is generated

### ISSUE THREAD

**Issue by jsachania** [nknapp/bootprint-swagger#8]
It will be nice if all the css code is put in html file so that only 1 file gets generated. It's easier to share one html file than the need of having two separate files to view the generated spec.

**Comment by nknapp** [comment]
I've tried this once, but there were some problems. I'm not sure what it was.
It might have been in development mode when including source-maps in the css.
I would accept a pull-request for that feature, but the css should only be included, when the `-d` flag is not set. However, this would probably be an issue in `bootprint`, not `bootprint-swagger`.
Can you reopen the issue there and link there?

**Comment by nknapp** [comment]
Substack's [html-inline](https://github.com/substack/html-inline) package seems to do the job very well.
I guess, it could be added easily, but for now, you could try the command-line tool:

```bash
npm install -g bootprint
npm install -g bootprint-swagger
bootprint swagger http://petstore.swagger.io/v2/swagger.json target

npm install -g html-inline
html-inline target/index.html >bundle.html
```

`bundle.html` should now be self-contained.

**Comment by nknapp** [comment]
html-inline has a size of 7.2 MB, which I don't want to add as a dependency right now. I have included my comment into the documentation instead.
